[package]
name = "veil-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
hex = "0.4"
rkyv = { version = "0.8", features = ["alloc"] }
ed25519-dalek = { version = "2", features = ["rand_core"] }
