[package]
name = "veil-server"
version = "0.1.0"
edition = "2024"

[dependencies]
veil-protocol = { path = "../veil-protocol" }

anyhow = "1"
axum = { version = "0.8", features = ["ws"] }
futures = "0.3"
itertools = "0.14"
tokio = { version = "1", features = ["full"] }
rkyv = "0.8"
